on: push
name: Build and test
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: arnested/go-version-action@v1
      id: go-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ steps.go-version.outputs.minimal }}
    - name: go test
      env:
        GO111MODULE: 'on'
      run: go test --verbose -race -cover -covermode=atomic ./...
