on: push
name: Build and test

permissions:
  contents: read

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arnested/go-version-action@v1
      id: version
    - name: Setup Go ${{ steps.version.outputs.go-mod-version }}.x
      uses: WillAbides/setup-go-faster@v1.10.1
      with:
        go-version: ${{ steps.version.outputs.go-mod-version }}.x
        ignore-local: true
    - name: go test
      env:
        GO111MODULE: 'on'
      run: go test --verbose -race -cover -covermode=atomic ./...
